Dev rose
eucossa-2022-sem2-web2-project/react-frontend-service-2022-s1 pull request #71
Opened 2022-11-09 07:17 UTC by Rose1845

2022-11-09 08:51 UTC, forinda commented
Please resolve linting that you've disabled to have a common convention terms
![rose](https://user-images.githubusercontent.com/55891685/200783939-8e75aa35-fae8-439b-a5e3-60133358e85a.png)
Enable them and resolve

2022-11-09 08:53 UTC, forinda requested changes
![rose](https://user-images.githubusercontent.com/55891685/200784250-ac317ce2-7874-4bd5-ad5c-16e61839bcf8.png)
We don't disable all conventions but only the ones that cannot conform fully. Please re-enable them and fix them

2022-11-09 08:56 UTC, Rose1845 commented
Okay..

On Wed, 9 Nov 2022, 11:53 AM Felix Orinda ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> [image: rose]
> <https://user-images.githubusercontent.com/55891685/200784250-ac317ce2-7874-4bd5-ad5c-16e61839bcf8.png>
> We don't disable all conventions but only the ones that cannot conform
> fully. Please re-enable them and fix them
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/eucossa-2022-sem2-web2-project/react-frontend-service-2022-s1/pull/71#pullrequestreview-1173603034>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AUAQUIMYMREUJHUXUJ4R3CTWHNRBJANCNFSM6AAAAAAR3DRFQM>
> .
> You are receiving this because you authored the thread.Message ID:
> <eucossa-2022-sem2-web2-project/react-frontend-service-2022-s1/pull/71/review/1173603034
> @github.com>
>

2022-11-10 08:16 UTC, forinda approved these changes

2022-11-10 08:17 UTC, merged